// Generated by Wrangler by running `wrangler types`

import type { TokenList } from "./src/do"

export interface Env {
	TOKENLIST: DurableObjectNamespace<TokenList>
	ASSETS: Fetcher
	ENVIRONMENT: string
	DO_TOKENLIST_NAME: string
	LUMINA_TOKEN_ENDPOINT_URL: string
	LUMINA_TOKEN_ENDPOINT_AUTH_TOKEN: string
	KV: KVNamespace
	SYNC_RATE_LIMITER: RateLimit
}
declare module "*.sql" {
	const value: string
	export default value
}
