#:schema node_modules/wrangler/config-schema.json
name                = "luminadex-contracts-cdn"
main                = "src/index.ts"
compatibility_date  = "2024-11-27"
compatibility_flags = ["nodejs_compat"]
vars                = { ENVIRONMENT = "production", DO_TOKENLIST_NAME = "db-prod-1" }
# Workers Static Assets
assets = { directory = "./public", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = false

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[[durable_objects.bindings]]
name       = "TOKENLIST"
class_name = "TokenList"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag                = "v1"
new_sqlite_classes = ["TokenList"]

# We need rules so we can import migrations in the next steps
[[rules]]
type        = "Text"
globs       = ["**/*.sql"]
fallthrough = true

# Schedule cron triggers:
[triggers]
# - At every 3rd minute
# - At 3PM on first day of the month
# - At 11:59PM on the last weekday of the month
crons = ["0 0 * * *"]


# # Worfklows are not working with vitest https://github.com/cloudflare/workers-sdk/issues/7414
# [[workflows]]
# # name of your workflow
# name = "sync-blockchain"
# # binding name env.MY_WORKFLOW
# binding = "SYNC_BLOCKCHAIN"
# # this is class that extends the Workflow class in src/index.ts
# class_name = "SyncBlockchain"
